### ISSUE TITLE
thumbnails for links are not rendering in 4.2.2

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeScraper#28]
i just noticed that the thumbnail icons for scraped pages are not rendering in the card views on my site. i am using 4.2.2 and on elgg 1.12.10. locally, they work fine - but on my server they do not and i just get an empty image holder.
the thumbnail files do appear to be in the hypescraper cache, so somewhere along the line they are not being retrieved correctly. so far i haven't found why.

**Comment by propertunist** [comment]
ah, from the log:
```
PHP message: PHP Fatal error:  Class 'hypeJunction\Servers\IconServer' not found in /var/www/html/ureka/mod/hypeApps/servers/icon.php on line 11" while reading response header from upstream, client: 87.115.131.169, server: www.ureka.org, request: "GET /mod/hypeApps/servers/icon.php?q=YTo2OntzOjM6InVpZCI7czozMjoiNmNjMzUxZDJhZWNlOTY4OTAyYjU4YzdkOTFjZTgzMWIiO3M6NDoicGF0aCI7czo1OToic2NyYXBlcl9jYWNoZS90aHVtYnMvNmNjMzUxZDJhZWNlOTY4OTAyYjU4YzdkOTFjZTgzMWIuMS5qcGciO3M6MToiZCI7aToxO3M6MzoiZHRzIjtpOjEyOTMwMjE5ODA7czoyOiJ0cyI7aToxNDU2MTQwMjM3O3M6MzoibWFjIjtzOjY0OiIyN2NlNmVlNjUxMjA5ZWY0MGU5NTY3ZDk0ZWM2NWRmYTc3MGZiNmQxZTliY2ViMzFmNGNjODU1MGZjMDE5MDcxIjt9 HTTP/1.1", upstream: "fastcgi://unix:/socket/php5-fpm.sock:", host: "www.ureka.org", referrer: "https://www.ureka.org/links/view/29337/ripe-near-me"
```

**Comment by propertunist** [comment]
hypeApps 4.3.5 is loaded prior to hypeScraper being loaded.

**Comment by hypeJunction** [comment]
I will check when I get a chance

**Comment by propertunist** [comment]
ok thanks. another error just arose out of nowhere. hypeapps failed with a similar error. i have had to disable both plugins for now since the site crashes with them enabled:
```
PHP Fatal error:  Class 'hypeJunction\Plugin' not found in /var/www/html/ureka/mod/hypeScraper/classes/hypeJunction/Scraper/Plugin.php on line 26" while reading response header from upstream, client: 87.115.131.169, server: www.ureka.org, request: "GET /activity HTTP/2.0", upstream: "fastcgi://unix:/socket/php5-fpm.sock:", host: "www.ureka.org", referrer: "https://www.ureka.org/activity"
```

**Comment by propertunist** [comment]
oh, that was the hypescraper error. there was another one for hypeApps that was shown on a white screen in the browser. i thought it would be the last error in the log, but apparently the hypeApps one isn't in the log at all.

**Comment by RiverVanRain** [comment]
@propertunist @hypeJunction Confirmed. The same issue

**Comment by propertunist** [comment]
@RiverVanRain  - ok, are you seeing both errors i posted here? or just one?

**Comment by propertunist** [comment]
erm.. now i am seeing a similar message for the AU_sets class -> AU\Sets\is_pinned() 
never seen this before and i have no idea what the cause is. maybe it is something to do with a change made to 1.12.10?

**Comment by propertunist** [comment]
what version of PHP are you using @RiverVanRain ?
i'm on 5.6.22 here

**Comment by propertunist** [comment]
oh - so the au_sets issue was due to a version mismatch here of that plugin. so not related to the hypescraper issue.

**Comment by RiverVanRain** [comment]
@propertunist 

> are you seeing both errors i posted here?
Just one error with Class 'hypeJunction\Servers\IconServer' if hypeApps before hypeScraper.
And both errors if hypeScraper moves up hypeApps

> what version of PHP are you using
5.5.33 on 1st server and 5.4 on 2nd server.
Similar issues on both productions.

**Comment by propertunist** [comment]
@RiverVanRain ok, thanks for the info. i thought the php version might be relevant after seeing the AU-sets class error, but since that is now fixed i conclude that the php version is not relevant and most likely there is something needing to be corrected in the hype plugins (or my use of them).

**Comment by RiverVanRain** [comment]
That's right and I think that issue related with hypeApps only.
Ismayil [fixed](https://github.com/hypeJunction/hypeApps/commit/704a0aa57e817aa38bb9e40ad3710ba69d52e44c) it already for hypeApps 5.1.1 but in early versions this error still there

**Comment by propertunist** [comment]
that doesn't explain why my local machine works fine and my remote machine is failing. but i will test the change here anyway.

**Comment by propertunist** [comment]
hm.. looks like there are more changes needed than just that one... i will see if older releases of hypeapps and hypescraper are any better.

**Comment by propertunist** [comment]
i have tested older verisons of hypeapps (4.3.4) and hypescraper (4.2.1) and am seeing the same problem with the icons not loading... i am sure these versions did work when i used them in the past. it seems likely to me that the problem is related to something that these plugins interact with outside of their own domain, like an external library that has changed or something like that.. i continue!

**Comment by hypeJunction** [comment]
Check the vendors folders for duplicate classes. Possible that composer grabbed later version of one of the plugins and classes are resolved incorrectly

**Comment by propertunist** [comment]
@hypeJunction the only vendors folder from the root of either plugin is in hypeApps and it has one subfolder called de77, which contains two unique files only.

**Comment by RiverVanRain** [comment]
@propertunist Did you installed [this version](https://github.com/hypeJunction/hypeApps/releases/download/4.3.5/hypeApps-4.3.5.zip) of hypeApps?

**Comment by propertunist** [comment]
@RiverVanRain that was the version i was using when i first found the icon problem, yes.

**Comment by RiverVanRain** [comment]
Solved for me.
You check now in mod\hypeApps\servers\icon.php with this code:
```
<?php

$base_dir = dirname(dirname(dirname(dirname(__FILE__))));
require_once $base_dir . '/engine/settings.php';
if (file_exists($base_dir . '/vendor/autoload.php')) {
	require_once $base_dir . '/vendor/autoload.php';
}

$plugin_root = dirname(dirname(__FILE__));
require_once $plugin_root . '/vendor/autoload.php';

global $CONFIG;
$conf = new \Elgg\Database\Config($CONFIG);

$server = new \hypeJunction\Servers\IconServer($CONFIG);
$server->serve();
```

**Comment by propertunist** [comment]
@RiverVanRain great, thanks - that works for me too. i still have the original problem that got me started looking at this code, which is that a specific icon is empty.. but most others are now working correctly. i will open another ticket for the other issue.

**Comment by propertunist** [comment]
actually, my local installation now fails with the fixed code, but my live servers work. i have removed all hypescraper code and hypeapps code from my local installation and then reinstalled the latest releases from github. the result is that my local install works straight away, without needing any fixes. so there is obviously some other issue here.

**Comment by RiverVanRain** [comment]
Maybe, cache is a reason?

**Comment by propertunist** [comment]
no, i am clearing the caches regularly.

**Comment by propertunist** [comment]
i think this last issue may be due to me misusing github a few days ago and causing some freaky things to happen with my local installation. somehow github magically managed to reverse some of my plugins to versions that i don't even have backups of and that github never had backups of!! i have no idea what that was about, but it is possible that the hype plugins got reverted to old versions without me knowing. i just downloaded the latest versions from my live server to my local server, including the RvR fix and now the local version works the same as the live version.

**Comment by propertunist** [comment]
since i am upgrading my site from 1.12 to 2.1 i am now facing this same problem again. the code that RvR provided doesn't work for me in 2.1, i just get extra errors.
this is the last issue i have before putting 2.1 live on my site, so i really want to fix it. the class loading system in the hype plugins is unfortunately almost unreadable to me though. any help is appreciated.

**Comment by propertunist** [comment]
ah, looks like this works:
```
$root = dirname(dirname(dirname(dirname(__FILE__))));

if (file_exists($root . '/vendor/autoload.php')) {
    require_once $root . '/vendor/autoload.php';
}
\Elgg\Application::start();
$plugin_root = dirname(dirname(__FILE__));
require_once $plugin_root . '/vendor/autoload.php';

$server = new \hypeJunction\Servers\IconServer();
$server->serve();
```

**Comment by hypeJunction** [comment]
2.2 will be released in a week or so and I can then loose hypeApps
dependency. Woohoo. So, not investing any time into 2.1 version. Sorry.

**Comment by propertunist** [comment]
oh ok, the code i pasted here appears to work fine anyway.
